import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const CATEGORIES = [
  // ═══════════════ Home & Household (15) ═══════════════
  { key: 'plumbing', group: 'home', sortOrder: 1, isOnline: false },
  { key: 'electrical', group: 'home', sortOrder: 2, isOnline: false },
  { key: 'carpentry', group: 'home', sortOrder: 3, isOnline: false },
  { key: 'painting', group: 'home', sortOrder: 4, isOnline: false },
  { key: 'cleaning', group: 'home', sortOrder: 5, isOnline: false },
  { key: 'gardening', group: 'home', sortOrder: 6, isOnline: false },
  { key: 'cooking', group: 'home', sortOrder: 7, isOnline: false },
  { key: 'childcare', group: 'home', sortOrder: 8, isOnline: false },
  { key: 'petSitting', group: 'home', sortOrder: 9, isOnline: false },
  { key: 'applianceRepair', group: 'home', sortOrder: 10, isOnline: false },
  { key: 'sewing', group: 'home', sortOrder: 11, isOnline: false },
  { key: 'laundry', group: 'home', sortOrder: 12, isOnline: false },
  { key: 'homeOrganizing', group: 'home', sortOrder: 13, isOnline: false },
  { key: 'insulation', group: 'home', sortOrder: 14, isOnline: false },
  { key: 'furnitureAssembly', group: 'home', sortOrder: 15, isOnline: false },

  // ═══════════════ Construction & Renovation (14) ═══════════════
  { key: 'masonry', group: 'construction', sortOrder: 1, isOnline: false },
  { key: 'plastering', group: 'construction', sortOrder: 2, isOnline: false },
  { key: 'tiling', group: 'construction', sortOrder: 3, isOnline: false },
  { key: 'roofing', group: 'construction', sortOrder: 4, isOnline: false },
  { key: 'foundation', group: 'construction', sortOrder: 5, isOnline: false },
  { key: 'welding', group: 'construction', sortOrder: 6, isOnline: false },
  { key: 'glazing', group: 'construction', sortOrder: 7, isOnline: false },
  { key: 'flooring', group: 'construction', sortOrder: 8, isOnline: false },
  { key: 'drywall', group: 'construction', sortOrder: 9, isOnline: false },
  { key: 'demolition', group: 'construction', sortOrder: 10, isOnline: false },
  { key: 'architecturalDesign', group: 'construction', sortOrder: 11, isOnline: true },
  { key: 'costEstimation', group: 'construction', sortOrder: 12, isOnline: true },
  { key: 'interiorDesign', group: 'construction', sortOrder: 13, isOnline: true },
  { key: 'landscapeDesign', group: 'construction', sortOrder: 14, isOnline: true },

  // ═══════════════ Business & Finance (15) ═══════════════
  { key: 'accounting', group: 'professional', sortOrder: 1, isOnline: true },
  { key: 'taxPlanning', group: 'professional', sortOrder: 2, isOnline: true },
  { key: 'bookkeeping', group: 'professional', sortOrder: 3, isOnline: true },
  { key: 'audit', group: 'professional', sortOrder: 4, isOnline: true },
  { key: 'businessConsulting', group: 'professional', sortOrder: 5, isOnline: true },
  { key: 'hrRecruiting', group: 'professional', sortOrder: 6, isOnline: true },
  { key: 'insurance', group: 'professional', sortOrder: 7, isOnline: true },
  { key: 'investmentAdvice', group: 'professional', sortOrder: 8, isOnline: true },
  { key: 'notaryServices', group: 'professional', sortOrder: 9, isOnline: false },
  { key: 'immigration', group: 'professional', sortOrder: 10, isOnline: true },
  { key: 'licensing', group: 'professional', sortOrder: 11, isOnline: true },
  { key: 'tenderSupport', group: 'professional', sortOrder: 12, isOnline: true },
  { key: 'marketing', group: 'professional', sortOrder: 13, isOnline: true },
  { key: 'projectManagement', group: 'professional', sortOrder: 14, isOnline: true },
  { key: 'salesSupport', group: 'professional', sortOrder: 15, isOnline: true },

  // ═══════════════ Legal (10) ═══════════════
  { key: 'legal', group: 'legal', sortOrder: 1, isOnline: true },
  { key: 'civilLaw', group: 'legal', sortOrder: 2, isOnline: true },
  { key: 'familyLaw', group: 'legal', sortOrder: 3, isOnline: true },
  { key: 'laborLaw', group: 'legal', sortOrder: 4, isOnline: true },
  { key: 'realEstateLaw', group: 'legal', sortOrder: 5, isOnline: true },
  { key: 'inheritanceLaw', group: 'legal', sortOrder: 6, isOnline: true },
  { key: 'trafficAccidentLaw', group: 'legal', sortOrder: 7, isOnline: true },
  { key: 'consumerProtection', group: 'legal', sortOrder: 8, isOnline: true },
  { key: 'mediation', group: 'legal', sortOrder: 9, isOnline: true },
  { key: 'criminalLaw', group: 'legal', sortOrder: 10, isOnline: true },

  // ═══════════════ Creative (18) ═══════════════
  { key: 'design', group: 'creative', sortOrder: 1, isOnline: true },
  { key: 'photography', group: 'creative', sortOrder: 2, isOnline: false },
  { key: 'videoProduction', group: 'creative', sortOrder: 3, isOnline: false },
  { key: 'videoEditing', group: 'creative', sortOrder: 4, isOnline: true },
  { key: 'animation', group: 'creative', sortOrder: 5, isOnline: true },
  { key: 'illustration', group: 'creative', sortOrder: 6, isOnline: true },
  { key: 'musicProduction', group: 'creative', sortOrder: 7, isOnline: true },
  { key: 'soundDesign', group: 'creative', sortOrder: 8, isOnline: true },
  { key: 'writing', group: 'creative', sortOrder: 9, isOnline: true },
  { key: 'editing', group: 'creative', sortOrder: 10, isOnline: true },
  { key: 'translation', group: 'creative', sortOrder: 11, isOnline: true },
  { key: 'webDesign', group: 'creative', sortOrder: 12, isOnline: true },
  { key: 'uiUxDesign', group: 'creative', sortOrder: 13, isOnline: true },
  { key: 'modeling3d', group: 'creative', sortOrder: 14, isOnline: true },
  { key: 'calligraphy', group: 'creative', sortOrder: 15, isOnline: true },
  { key: 'drawing', group: 'creative', sortOrder: 16, isOnline: false },
  { key: 'voiceActing', group: 'creative', sortOrder: 17, isOnline: true },
  { key: 'podcasting', group: 'creative', sortOrder: 18, isOnline: true },

  // ═══════════════ Health & Wellness (18) ═══════════════
  { key: 'firstAid', group: 'health', sortOrder: 1, isOnline: false },
  { key: 'nursing', group: 'health', sortOrder: 2, isOnline: false },
  { key: 'psychology', group: 'health', sortOrder: 3, isOnline: true },
  { key: 'nutrition', group: 'health', sortOrder: 4, isOnline: true },
  { key: 'fitness', group: 'health', sortOrder: 5, isOnline: false },
  { key: 'massage', group: 'health', sortOrder: 6, isOnline: false },
  { key: 'yoga', group: 'health', sortOrder: 7, isOnline: true },
  { key: 'rehabilitation', group: 'health', sortOrder: 8, isOnline: false },
  { key: 'dentistry', group: 'health', sortOrder: 9, isOnline: false },
  { key: 'ophthalmology', group: 'health', sortOrder: 10, isOnline: false },
  { key: 'dermatology', group: 'health', sortOrder: 11, isOnline: false },
  { key: 'speechTherapy', group: 'health', sortOrder: 12, isOnline: true },
  { key: 'osteopathy', group: 'health', sortOrder: 13, isOnline: false },
  { key: 'aromatherapy', group: 'health', sortOrder: 14, isOnline: false },
  { key: 'elderlyCare', group: 'health', sortOrder: 15, isOnline: false },
  { key: 'physiotherapy', group: 'health', sortOrder: 16, isOnline: false },
  { key: 'mentalHealthSupport', group: 'health', sortOrder: 17, isOnline: true },
  { key: 'homeopathy', group: 'health', sortOrder: 18, isOnline: true },

  // ═══════════════ Beauty & Care (10) ═══════════════
  { key: 'hairdressing', group: 'beauty', sortOrder: 1, isOnline: false },
  { key: 'manicurePedicure', group: 'beauty', sortOrder: 2, isOnline: false },
  { key: 'makeupArtistry', group: 'beauty', sortOrder: 3, isOnline: false },
  { key: 'cosmetology', group: 'beauty', sortOrder: 4, isOnline: false },
  { key: 'lashExtensions', group: 'beauty', sortOrder: 5, isOnline: false },
  { key: 'personalStylist', group: 'beauty', sortOrder: 6, isOnline: true },
  { key: 'barber', group: 'beauty', sortOrder: 7, isOnline: false },
  { key: 'hairRemoval', group: 'beauty', sortOrder: 8, isOnline: false },
  { key: 'facialMassage', group: 'beauty', sortOrder: 9, isOnline: false },
  { key: 'tattoo', group: 'beauty', sortOrder: 10, isOnline: false },

  // ═══════════════ Transport & Logistics (12) ═══════════════
  { key: 'driving', group: 'transport', sortOrder: 1, isOnline: false },
  { key: 'moving', group: 'transport', sortOrder: 2, isOnline: false },
  { key: 'delivery', group: 'transport', sortOrder: 3, isOnline: false },
  { key: 'towTruck', group: 'transport', sortOrder: 4, isOnline: false },
  { key: 'freightTransport', group: 'transport', sortOrder: 5, isOnline: false },
  { key: 'courierService', group: 'transport', sortOrder: 6, isOnline: false },
  { key: 'airTickets', group: 'transport', sortOrder: 7, isOnline: true },
  { key: 'airportTransfer', group: 'transport', sortOrder: 8, isOnline: false },
  { key: 'carRental', group: 'transport', sortOrder: 9, isOnline: false },
  { key: 'carpooling', group: 'transport', sortOrder: 10, isOnline: false },
  { key: 'boatTransport', group: 'transport', sortOrder: 11, isOnline: false },
  { key: 'logisticsPlanning', group: 'transport', sortOrder: 12, isOnline: true },

  // ═══════════════ Auto & Vehicles (12) ═══════════════
  { key: 'autoMechanic', group: 'auto', sortOrder: 1, isOnline: false },
  { key: 'bodyRepair', group: 'auto', sortOrder: 2, isOnline: false },
  { key: 'tireService', group: 'auto', sortOrder: 3, isOnline: false },
  { key: 'autoElectrics', group: 'auto', sortOrder: 4, isOnline: false },
  { key: 'carDiagnostics', group: 'auto', sortOrder: 5, isOnline: false },
  { key: 'carTuning', group: 'auto', sortOrder: 6, isOnline: false },
  { key: 'carWash', group: 'auto', sortOrder: 7, isOnline: false },
  { key: 'carPolishing', group: 'auto', sortOrder: 8, isOnline: false },
  { key: 'motorcycleRepair', group: 'auto', sortOrder: 9, isOnline: false },
  { key: 'bicycleRepair', group: 'auto', sortOrder: 10, isOnline: false },
  { key: 'boatRepair', group: 'auto', sortOrder: 11, isOnline: false },
  { key: 'carInspection', group: 'auto', sortOrder: 12, isOnline: false },

  // ═══════════════ IT & Digital (22) ═══════════════
  { key: 'webDev', group: 'digital', sortOrder: 1, isOnline: true },
  { key: 'mobileDev', group: 'digital', sortOrder: 2, isOnline: true },
  { key: 'sysAdmin', group: 'digital', sortOrder: 3, isOnline: true },
  { key: 'dataRecovery', group: 'digital', sortOrder: 4, isOnline: true },
  { key: 'socialMedia', group: 'digital', sortOrder: 5, isOnline: true },
  { key: 'seo', group: 'digital', sortOrder: 6, isOnline: true },
  { key: 'computerSetup', group: 'digital', sortOrder: 7, isOnline: false },
  { key: 'networkSetup', group: 'digital', sortOrder: 8, isOnline: false },
  { key: 'cybersecurity', group: 'digital', sortOrder: 9, isOnline: true },
  { key: 'cloudServices', group: 'digital', sortOrder: 10, isOnline: true },
  { key: 'databases', group: 'digital', sortOrder: 11, isOnline: true },
  { key: 'devops', group: 'digital', sortOrder: 12, isOnline: true },
  { key: 'aiMl', group: 'digital', sortOrder: 13, isOnline: true },
  { key: 'dataAnalytics', group: 'digital', sortOrder: 14, isOnline: true },
  { key: 'techSupport', group: 'digital', sortOrder: 15, isOnline: true },
  { key: 'iot', group: 'digital', sortOrder: 16, isOnline: true },
  { key: 'blockchain', group: 'digital', sortOrder: 17, isOnline: true },
  { key: 'qaTestin', group: 'digital', sortOrder: 18, isOnline: true },
  { key: 'gameDev', group: 'digital', sortOrder: 19, isOnline: true },
  { key: 'automation', group: 'digital', sortOrder: 20, isOnline: true },
  { key: 'erp', group: 'digital', sortOrder: 21, isOnline: true },
  { key: 'techWriting', group: 'digital', sortOrder: 22, isOnline: true },

  // ═══════════════ Education & Tutoring (16) ═══════════════
  { key: 'mathTutoring', group: 'education', sortOrder: 1, isOnline: true },
  { key: 'languageTutoring', group: 'education', sortOrder: 2, isOnline: true },
  { key: 'physicsTutoring', group: 'education', sortOrder: 3, isOnline: true },
  { key: 'chemistryTutoring', group: 'education', sortOrder: 4, isOnline: true },
  { key: 'musicLessons', group: 'education', sortOrder: 5, isOnline: false },
  { key: 'examPrep', group: 'education', sortOrder: 6, isOnline: true },
  { key: 'preschoolEducation', group: 'education', sortOrder: 7, isOnline: false },
  { key: 'speedReading', group: 'education', sortOrder: 8, isOnline: true },
  { key: 'publicSpeaking', group: 'education', sortOrder: 9, isOnline: true },
  { key: 'mentoring', group: 'education', sortOrder: 10, isOnline: true },
  { key: 'coaching', group: 'education', sortOrder: 11, isOnline: true },
  { key: 'codingForBeginners', group: 'education', sortOrder: 12, isOnline: true },
  { key: 'chess', group: 'education', sortOrder: 13, isOnline: true },
  { key: 'robotics', group: 'education', sortOrder: 14, isOnline: false },
  { key: 'artClasses', group: 'education', sortOrder: 15, isOnline: false },
  { key: 'drivingLessons', group: 'education', sortOrder: 16, isOnline: false },

  // ═══════════════ Events & Entertainment (12) ═══════════════
  { key: 'eventOrganizing', group: 'events', sortOrder: 1, isOnline: false },
  { key: 'weddingPlanning', group: 'events', sortOrder: 2, isOnline: false },
  { key: 'djServices', group: 'events', sortOrder: 3, isOnline: false },
  { key: 'soundOperator', group: 'events', sortOrder: 4, isOnline: false },
  { key: 'eventDecor', group: 'events', sortOrder: 5, isOnline: false },
  { key: 'floristry', group: 'events', sortOrder: 6, isOnline: false },
  { key: 'catering', group: 'events', sortOrder: 7, isOnline: false },
  { key: 'equipmentRental', group: 'events', sortOrder: 8, isOnline: false },
  { key: 'fundraising', group: 'events', sortOrder: 9, isOnline: true },
  { key: 'volunteering', group: 'events', sortOrder: 10, isOnline: false },
  { key: 'hostingMC', group: 'events', sortOrder: 11, isOnline: false },
  { key: 'partyPlanning', group: 'events', sortOrder: 12, isOnline: false },

  // ═══════════════ Pets & Animals (10) ═══════════════
  { key: 'veterinary', group: 'pets', sortOrder: 1, isOnline: false },
  { key: 'petGrooming', group: 'pets', sortOrder: 2, isOnline: false },
  { key: 'dogTraining', group: 'pets', sortOrder: 3, isOnline: false },
  { key: 'petBoarding', group: 'pets', sortOrder: 4, isOnline: false },
  { key: 'dogWalking', group: 'pets', sortOrder: 5, isOnline: false },
  { key: 'animalPsychology', group: 'pets', sortOrder: 6, isOnline: true },
  { key: 'aquaristics', group: 'pets', sortOrder: 7, isOnline: false },
  { key: 'cynology', group: 'pets', sortOrder: 8, isOnline: false },
  { key: 'birdKeeping', group: 'pets', sortOrder: 9, isOnline: false },
  { key: 'exoticPets', group: 'pets', sortOrder: 10, isOnline: false },

  // ═══════════════ Outdoor & Sports (12) ═══════════════
  { key: 'hiking', group: 'outdoor', sortOrder: 1, isOnline: false },
  { key: 'fishing', group: 'outdoor', sortOrder: 2, isOnline: false },
  { key: 'hunting', group: 'outdoor', sortOrder: 3, isOnline: false },
  { key: 'surfing', group: 'outdoor', sortOrder: 4, isOnline: false },
  { key: 'skiing', group: 'outdoor', sortOrder: 5, isOnline: false },
  { key: 'scubaDiving', group: 'outdoor', sortOrder: 6, isOnline: false },
  { key: 'rockClimbing', group: 'outdoor', sortOrder: 7, isOnline: false },
  { key: 'sailing', group: 'outdoor', sortOrder: 8, isOnline: false },
  { key: 'cycling', group: 'outdoor', sortOrder: 9, isOnline: false },
  { key: 'martialArts', group: 'outdoor', sortOrder: 10, isOnline: false },
  { key: 'camping', group: 'outdoor', sortOrder: 11, isOnline: false },
  { key: 'horseRiding', group: 'outdoor', sortOrder: 12, isOnline: false },

  // ═══════════════ Agriculture (10) ═══════════════
  { key: 'agronomy', group: 'agriculture', sortOrder: 1, isOnline: false },
  { key: 'animalHusbandry', group: 'agriculture', sortOrder: 2, isOnline: false },
  { key: 'beekeeping', group: 'agriculture', sortOrder: 3, isOnline: false },
  { key: 'winemaking', group: 'agriculture', sortOrder: 4, isOnline: false },
  { key: 'greenhouse', group: 'agriculture', sortOrder: 5, isOnline: false },
  { key: 'irrigation', group: 'agriculture', sortOrder: 6, isOnline: false },
  { key: 'organicFarming', group: 'agriculture', sortOrder: 7, isOnline: false },
  { key: 'soilAnalysis', group: 'agriculture', sortOrder: 8, isOnline: true },
  { key: 'pestControl', group: 'agriculture', sortOrder: 9, isOnline: false },
  { key: 'mushrooming', group: 'agriculture', sortOrder: 10, isOnline: false },
];

async function main() {
  for (const cat of CATEGORIES) {
    await prisma.skillCategory.upsert({
      where: { key: cat.key },
      create: cat,
      update: { group: cat.group, sortOrder: cat.sortOrder, isOnline: cat.isOnline },
    });
  }
  console.log(`Seeded ${CATEGORIES.length} skill categories`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
